# Generated by Django 2.0.7 on 2018-07-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Digest_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_event', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events_foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('is_it_cover', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Events_participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Events_subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Events_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Points_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('is_it_org', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=80)),
                ('quantity_of_points', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.City')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('raiting_points', models.IntegerField()),
                ('blocked', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.City')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Rank')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='points_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='events_subscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='events_participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='events_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Events_type'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='digest_list',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Events_type'),
        ),
        migrations.AddField(
            model_name='digest_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user_from', 'user_to')},
        ),
        migrations.AlterUniqueTogether(
            name='points_history',
            unique_together={('user', 'event', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='events_subscriber',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='events_participant',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'event', 'date')},
        ),
    ]
