# Generated by Django 2.0.7 on 2018-08-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
