# Generated by Django 2.0.7 on 2018-08-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_user_django_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsphoto',
            name='photo',
            field=models.ImageField(upload_to='media/event_images'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='volunteer.City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='volunteer.City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='volunteer.Rank'),
        ),
    ]
