# Generated by Django 2.0.7 on 2018-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20180902_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='image',
            field=models.FileField(upload_to='media/currency'),
        ),
    ]
