# Generated by Django 2.0.7 on 2018-09-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20180807_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsOrgTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('recommended_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='district',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.City'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='events_or_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_part',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='min_part',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recommended_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.AddField(
            model_name='eventsorgtask',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.Status'),
        ),
    ]
