# Generated by Django 2.0.7 on 2018-09-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20180901_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.Status', verbose_name='Статус'),
        ),
    ]
