# Generated by Django 2.0.7 on 2018-09-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20180902_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/achievements'),
        ),
    ]
