# Generated by Django 2.0.7 on 2018-09-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_achievement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('achievement', 'user')},
        ),
    ]
