# Generated by Django 2.0.7 on 2018-09-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_auto_20180906_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointslist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
