# Generated by Django 2.0.7 on 2018-09-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_auto_20180906_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decreasepointsinfo',
            name='decrease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.DecreasePointsType'),
        ),
    ]
