# Generated by Django 2.0.7 on 2018-09-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_auto_20180906_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointslist',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteer.Currency'),
            preserve_default=False,
        ),
    ]
