# Generated by Django 2.0.7 on 2018-09-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_pointslist_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_image',
            field=models.FileField(blank=True, null=True, upload_to='media/achievements'),
        ),
        migrations.AddField(
            model_name='league',
            name='user_frame',
            field=models.FileField(blank=True, null=True, upload_to='media/achievements'),
        ),
    ]
