# Generated by Django 2.0.7 on 2018-09-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20180830_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='media/currency')),
                ('type_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.EventsType')),
            ],
        ),
        migrations.CreateModel(
            name='DecreasePointsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Achievement')),
            ],
        ),
        migrations.CreateModel(
            name='DecreasePointsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decrease_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncreasePointsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IncreasePointsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increase_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=80)),
                ('quantity_achievement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PointsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('increase', models.BooleanField(default=True)),
                ('points_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Currency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pointshistory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pointshistory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='pointshistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='raiting_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.Status', verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='PointsHistory',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.AddField(
            model_name='userpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='pointslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.User'),
        ),
        migrations.AddField(
            model_name='increasepointsinfo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Event'),
        ),
        migrations.AddField(
            model_name='increasepointsinfo',
            name='increase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.PointsList'),
        ),
        migrations.AddField(
            model_name='increasepointsinfo',
            name='increase_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.IncreasePointsType'),
        ),
        migrations.AddField(
            model_name='decreasepointsinfo',
            name='decrease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.PointsList'),
        ),
        migrations.AddField(
            model_name='decreasepointsinfo',
            name='decrease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.IncreasePointsType'),
        ),
        migrations.AddField(
            model_name='achievementvalue',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Currency'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.League'),
        ),
        migrations.AddField(
            model_name='user',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.League'),
        ),
        migrations.AlterUniqueTogether(
            name='userpoint',
            unique_together={('user', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='achievementvalue',
            unique_together={('achievement', 'currency')},
        ),
    ]
